// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateCharlesKey(arg1) {
  return window['go']['main']['App']['GenerateCharlesKey'](arg1);
}
